version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 1972
      - 52773:52773
      - 8888:8888
    volumes:
      - ./:/irisdev/app
